name: CI / SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  syntax-check:
    name: Build & Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and check syntax (skip tests & checkstyle)
        id: build
        run: |
          mvn verify -DskipTests -Dcheckstyle.skip=true -Dnohttp.checkstyle.skip=true -Dspring-javaformat.skip=true
        continue-on-error: true

      - name: Send Discord notification on failure
        if: steps.build.outcome != 'success'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1373962801684676618/7mbjxZjYXVcUsiBEutRuLLeGEHvkVNoZ2hkmfqH_zipVql9diF1VT_66iiY3Va_5llyb
          title: "❌ Build Failed"
          description: "Syntax check failed in **${{ github.repository }}**"
          color: 0xff0000
          username: CI/CD Bot
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

      - name: Upload target/ directory as artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: mvn-target
          path: target/
          retention-days: 1

  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: syntax-check
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: mvn-target
          path: target/

      - name: Run SonarCloud Analysis
        id: sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PROJECT_KEY="antnm-splus_java-web-small"
          echo "Using SonarCloud project key: $PROJECT_KEY"

          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=$PROJECT_KEY \
            -Dsonar.projectName=spring-petclinic \
            -Dsonar.organization=antnm-splus \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dcheckstyle.skip=true \
            -Dnohttp.checkstyle.skip=true \
            -Dspring-javaformat.skip=true \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.scm.disabled=true
        continue-on-error: true

      - name: Get SonarCloud quality gate result
        id: quality_gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          PROJECT_KEY="antnm-splus_java-web-small"

          # Determine branch or PR
          if [[ "$GITHUB_REF" == refs/pull/* ]]; then
            PR_NUMBER=$(echo $GITHUB_REF | sed -n 's/refs\/pull\/\([0-9]*\)\/merge/\1/p')
            echo "Running on PR #$PR_NUMBER"
            PARAM="pullRequest=$PR_NUMBER"
          else
            BRANCH=${GITHUB_REF#refs/heads/}
            echo "Running on branch $BRANCH"
            PARAM="branch=$BRANCH"
          fi

          # Wait for quality gate to be computed (max 2 minutes)
          echo "Waiting for quality gate results..."
          MAX_ATTEMPTS=24
          ATTEMPT=0

          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            # Get quality gate status
            QG_RESULT=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&$PARAM")
            
            # Check if we got valid JSON with conditions
            if echo "$QG_RESULT" | jq -e '.projectStatus.conditions' >/dev/null 2>&1; then
              CONDITIONS_COUNT=$(echo "$QG_RESULT" | jq -r '.projectStatus.conditions | length // 0')
              STATUS=$(echo "$QG_RESULT" | jq -r '.projectStatus.status // "NONE"')
              
              if [ "$STATUS" != "NONE" ] && [ "$CONDITIONS_COUNT" -gt 0 ]; then
                echo "Quality gate computed with status: $STATUS"
                break
              fi
            fi
            
            sleep 5
            ATTEMPT=$((ATTEMPT+1))
            echo "Waiting for quality gate (attempt $ATTEMPT/$MAX_ATTEMPTS)..."
          done

          # Save status to output
          STATUS=$(echo "$QG_RESULT" | jq -r '.projectStatus.status // "NONE"')
          echo "status=$STATUS" >> $GITHUB_OUTPUT

          # Get code smells
          CODE_SMELLS=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/measures/component?component=$PROJECT_KEY&metricKeys=code_smells" | 
                        jq -r '.component.measures[0].value // "0"')

          # Process conditions
          FAILED_METRICS=""
          PASSED_METRICS=""
          OTHER_METRICS="- Code Smells: ${CODE_SMELLS}"

          CONDITIONS=$(echo "$QG_RESULT" | jq -r '.projectStatus.conditions')
          CONDITIONS_COUNT=$(echo "$CONDITIONS" | jq -r 'length // 0')

          if [ "$CONDITIONS_COUNT" -gt 0 ]; then
            echo "Processing $CONDITIONS_COUNT conditions"
            
            # Process each condition
            for i in $(seq 0 $(($CONDITIONS_COUNT - 1))); do
              CONDITION=$(echo "$CONDITIONS" | jq -r ".[$i] // {}")
              
              # Skip empty conditions
              if [ "$CONDITION" = "{}" ] || [ -z "$CONDITION" ]; then
                continue
              fi
              
              # Extract values
              METRIC_KEY=$(echo "$CONDITION" | jq -r '.metricKey // "unknown"')
              ACTUAL_VALUE=$(echo "$CONDITION" | jq -r '.actualValue // "0"')
              ERROR_THRESHOLD=$(echo "$CONDITION" | jq -r '.errorThreshold // "0"')
              COMPARATOR=$(echo "$CONDITION" | jq -r '.comparator // "EQ"')
              STATUS=$(echo "$CONDITION" | jq -r '.status // "NONE"')
              
              # Format user-friendly metric name
              case "$METRIC_KEY" in
                "new_coverage") METRIC_NAME="Coverage on New Code"; UNIT="%" ;;
                "new_duplicated_lines_density") METRIC_NAME="Duplication on New Code"; UNIT="%" ;;
                "new_reliability_rating") METRIC_NAME="Reliability Rating"; UNIT="" ;;
                "new_security_rating") METRIC_NAME="Security Rating"; UNIT="" ;;
                "new_maintainability_rating") METRIC_NAME="Maintainability Rating"; UNIT="" ;;
                "new_security_hotspots_reviewed") METRIC_NAME="Security Hotspots Reviewed"; UNIT="%" ;;
                *) METRIC_NAME="$METRIC_KEY"; UNIT="" ;;
              esac
              
              # Format comparator
              DISPLAY_COMPARATOR=$([[ "$COMPARATOR" = "LT" ]] && echo "≥" || 
                                  [[ "$COMPARATOR" = "GT" ]] && echo "≤" || 
                                  [[ "$COMPARATOR" = "EQ" ]] && echo "=" || 
                                  echo "$COMPARATOR")
              
              # Create formatted text
              CONDITION_TEXT="- $METRIC_NAME: $ACTUAL_VALUE$UNIT (required $DISPLAY_COMPARATOR $ERROR_THRESHOLD$UNIT)"
              
              # Add to appropriate output
              if [ "$STATUS" = "OK" ]; then
                PASSED_METRICS="${PASSED_METRICS}${CONDITION_TEXT}\n"
              elif [ "$STATUS" = "ERROR" ]; then
                FAILED_METRICS="${FAILED_METRICS}${CONDITION_TEXT}\n"
              else
                OTHER_METRICS="${OTHER_METRICS}\n${CONDITION_TEXT}"
              fi
            done
          else
            OTHER_METRICS="${OTHER_METRICS}\n- No quality gate conditions found"
          fi

          # Count metrics
          FAILED_COUNT=$(echo -e "$FAILED_METRICS" | grep -c "^-" || echo 0)
          PASSED_COUNT=$(echo -e "$PASSED_METRICS" | grep -c "^-" || echo 0)

          # Set outputs
          echo "failed_count=$FAILED_COUNT" >> $GITHUB_OUTPUT
          echo "passed_count=$PASSED_COUNT" >> $GITHUB_OUTPUT

          echo "failed_metrics<<EOF" >> $GITHUB_OUTPUT
          if [ "$FAILED_COUNT" -gt 0 ]; then
            echo -e "$FAILED_METRICS" >> $GITHUB_OUTPUT
          else
            echo "No failed conditions" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

          echo "passed_metrics<<EOF" >> $GITHUB_OUTPUT
          if [ "$PASSED_COUNT" -gt 0 ]; then
            echo -e "$PASSED_METRICS" >> $GITHUB_OUTPUT
          else
            echo "No passed conditions" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

          echo "other_metrics<<EOF" >> $GITHUB_OUTPUT
          echo -e "$OTHER_METRICS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Discord notification for SonarCloud
        if: always()
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          webhook: https://discord.com/api/webhooks/1373962801684676618/7mbjxZjYXVcUsiBEutRuLLeGEHvkVNoZ2hkmfqH_zipVql9diF1VT_66iiY3Va_5llyb
          title: "${{ steps.quality_gate.outputs.status == 'OK' && '✅ SonarCloud Quality Gate: SUCCESS' || '❌ SonarCloud Quality Gate: FAILED' }}"
          description: |
            Quality Gate Analysis for **${{ github.repository }}**
          color: "${{ steps.quality_gate.outputs.status == 'OK' && '0x00ff00' || '0xff0000' }}"
          username: SonarCloud Bot
          url: https://sonarcloud.io/dashboard?id=antnm-splus_java-web-small
          avatar_url: https://sonarcloud.io/apple-touch-icon-180x180.png
          nodetail: false
          content: |
            ### Quality Gate Details

            #### Failed Conditions
            ${{ steps.quality_gate.outputs.failed_metrics }}

            #### Passed Conditions
            ${{ steps.quality_gate.outputs.passed_metrics }}

            #### Other Metrics
            ${{ steps.quality_gate.outputs.other_metrics }}

            [View Full Report on SonarCloud](https://sonarcloud.io/dashboard?id=antnm-splus_java-web-small)

    continue-on-error: true
